config/routes.rb
Rails.application.routes.draw do
  root 'students#index'
  resources :students
  # I spend four hours searching for a bug, when I try to delete a resource
  # and the bug was in the line three, I wrote resource instead of resources
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def destroy
    Student.find(params[:id]).destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LastProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>Students#index</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hobby</th>
      <th>Pokemon</th>
      <th>Lucky number</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
  <tr>
      <td><%= student.name %></td>
      <td><%= student.hobby %></td>
      <td><%= student.pokemon %></td>
      <td><%= student.lucky_number %></td>
      <td><%= student.birthday %></td>

      <td><%= link_to 'Destroy', student_path(student[:id]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
    <% end %>
  </tbody>
</table>

<br>